### ISSUE TITLE
`spin k8s scaffold`: variables support

### ISSUE THREAD

**Issue by bacongobbler** [spinkube/spin-plugin-kube#31]
```
spin k8s scaffold --variable foo=bar --variable car=star
```

https://github.com/spinkube/documentation/blob/main/content/en/docs/spin-operator/tutorials/assigning-variables.md

**Comment by kate-goldenring** [comment]
@bacongobbler can I take this on?

**Comment by bacongobbler** [comment]
Absolutely!
