### ISSUE TITLE
Plugin 0.3.0 still references core.spinoperator.dev/v1alpha1

### ISSUE THREAD

**Issue by jandubois** [spinkube/spin-plugin-kube#93]
For example (using spinkube operator 0.4.0):

```console
$ spin kube --version
kube version 0.3.0
$ spin kube deploy --from ghcr.io/spinkube/containerd-shim-spin/examples/spin-rust-hello:v0.13.0
Error: no matches for kind "SpinApp" in version "core.spinoperator.dev/v1alpha1"
Usage:
  kube deploy [flags]
…
```

Using the `--dry-run` option and piping into `kubectl apply -f -` works.

I believe the root cause is that the plugin still links to `spin-operator` 0.1.0 in the `go.mod` file: https://github.com/spinkube/spin-plugin-kube/blob/6f4c9c63ec3210680284c717a69906554912bcbe/go.mod#L13

**Comment by bacongobbler** [comment]
Yes, that would indeed be the issue. Thanks for catching this.
